### ISSUE TITLE
Continuous Integration Testing

### ISSUE THREAD

**Issue by evan-bradley** [evan-bradley/brandcentralstation#17]
Improve testing to ensure that new commits don't break anything.
https://github.com/travis-ci/travis-ci

**Comment by evan-bradley** [comment]
If you know anything about this, feel free to add input/start with it.

**Comment by jpherkness** [comment]
https://github.com/dwyl/learn-travis This is what we would use.

**Comment by jpherkness** [comment]
Closing this for now. We can reopen if we have time.
