### ISSUE TITLE
Create Recover Password Page

### ISSUE THREAD

**Issue by demottmatthew** [evan-bradley/brandcentralstation#20]

**Comment by demottmatthew** [comment]
This function currently sends an email to the entered email if it is found in our database and when the link is clicked on in the email it takes you to the reset password page. When a password is entered, it verifies the token in the database and pulls the USER_ID that is associated with that token and changes the password. The one problem, I believe, has to do with the response being sent from the API. The front end is checking to see what the response says and based on that routes the user to the login page or not. It currently does not route the user to the login page after the reset password button is clicked even though the password is successfully changed.

**Comment by jpherkness** [comment]
```
pool.query(CHANGEPASSWORD_Q, [ hash, results[0].USER_ID ], (err, result) => {
  if (err) {
    console.log(err);
    throw err;
  } 
});
```
should have been:
```
pool.query(CHANGEPASSWORD_Q, [ hash, results[0].USER_ID ], callback);
```
I also fixed the javascript format.

**Comment by jpherkness** [comment]
We might want to invalidate the password reset tokens after they have been used, and after a certain amount of time. But for now this is good.
