### ISSUE TITLE
Registration input validation

### ISSUE THREAD

**Issue by jpherkness** [evan-bradley/brandcentralstation#6]
The following input validation must take place:
- First name and last name are optional.
- Username must be non-empty.
- Passwords must match and contain at least 8 characters.

**Comment by jpherkness** [comment]
Should the username be unique across all users? @demottmatthew @evan-bradley If this should be the case, then we need to add validation for unique usernames.

**Comment by evan-bradley** [comment]
@jpherkness Yeah, they should be if you want to follow people. It's just way simpler on so many levels.

**Comment by jpherkness** [comment]
The registration API endpoint return an error if the username is already taken. The message would have to be displayed at the top. If we want the error message displayed on the username input, we would want to have a separate API endpoint. I would be okay with that.
