### ISSUE TITLE
Channel Page is too long for phone screens

### ISSUE THREAD

**Issue by evan-bradley** [evan-bradley/brandcentralstation#74]
Currently the user has to scroll to view the whole page.
<img width="402" alt="screen shot 2017-11-09 at 13 04 55" src="https://user-images.githubusercontent.com/11745660/32621773-e6434b6a-c54e-11e7-9d1d-3d7eadddbbef.png">
<img width="396" alt="screen shot 2017-11-09 at 13 05 03" src="https://user-images.githubusercontent.com/11745660/32621777-e8187e42-c54e-11e7-9b6c-81e7d73d60e8.png">

Recommendation: Don't display the product description, leave it to the product detail view, and move the title and unsubscribe buttons to the slideout bar, or compact them somehow.
<img width="398" alt="screen shot 2017-11-09 at 13 06 10" src="https://user-images.githubusercontent.com/11745660/32621795-f163e28e-c54e-11e7-8119-5086b80e3044.png">

**Comment by jpherkness** [comment]
I have a better solution planned, but it will take some refactoring. For now, I'm not displaying the description and shrinking the text size. This seems to make it fit better. We can reopen the issue if/when we have time.
