### ISSUE TITLE
Stuck on like page

### ISSUE THREAD

**Issue by kschrade** [evan-bradley/brandcentralstation#83]
A co worker was testing out our site and found that if he got a item a second time and liked the produce it threw a error in the background. It would try to insert a like into the table a second time violating the PK of the like table.
![2017-11-13 12_20_29-938b1e40 png - photos](https://user-images.githubusercontent.com/16599960/32739178-15cc7b1a-c86d-11e7-804b-94dc6883e8e6.png)

**Comment by demottmatthew** [comment]
Yeah we know about this. Once we get the machine learning up and going it wont suggest the same product twice.

**Comment by jpherkness** [comment]
Can we add some validation to the like and dislike endpoints anyway?

**Comment by demottmatthew** [comment]
I have it integrated now so that it does do that. But that change hasn't been pulled to the server.
