### ISSUE TITLE
Move documentation into a separate folder

### ISSUE THREAD

**Issue by jpherkness** [evan-bradley/brandcentralstation#9]
Currently, the documentation is contained in the project root directory. These files should be moved to a new folder called `/documentation/sprint-2/...` or `/documentation/sprint-3`. The project should look like:
- /server
  - server stuff....
- /client
  - client stuff....
- /documentation
  - /sprint-1
    - sprint 1 stuff....
  - /sprint-2
    - sprint 2 stuff....

**Comment by demottmatthew** [comment]
I created the new folder and moved the files to the proper locations.
